# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ci-pipeline

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Node.js dependencies
        run: npm ci

      # - name: Lint
      #   run: npm run lint:check

      - name: Prettier
        run: npm run prettier:check

      - name: Build API
        run: npm run build:api

      - name: Build FE
        run: npm run build:fe

      - name: Build-storybook Common-ui
        run: npm run build-storybook:common-ui

      - name: Test API
        run: npm run test:api

      - name: Test FE
        run: npm run test:fe

      - name: Test Models-server
        run: npm run test:models-server

      - name: Test Utils
        run: npm run test:utils
